Pmodules/modulecmd.bash.in: subcommand_load(): do not print the error message from modulecmd.bin

diff --git a/Pmodules/modulecmd.bash.in b/Pmodules/modulecmd.bash.in
--- a/Pmodules/modulecmd.bash.in
+++ b/Pmodules/modulecmd.bash.in
@@ -825,7 +825,7 @@ subcommand_load() {
 		echo "${output}"
 		eval "${output}"
 		local error=$( < "${tmpfile}")
-		echo "${error}" 1>&2
+		#echo "${error}" 1>&2
 		if [[ "${error}" =~ ":ERROR:" ]]; then
 			std::info "${CMD} load: failed -- ${m}"
 		fi
