echo text to stderr in subcommand load

diff --git a/Pmodules/modulecmd.bash.in b/Pmodules/modulecmd.bash.in
--- a/Pmodules/modulecmd.bash.in
+++ b/Pmodules/modulecmd.bash.in
@@ -519,7 +519,7 @@ subcommand_load() {
                 fi
                 if [[ "${Shell}" == "bash" ]]; then
                         echo "${output}"
-                        echo "${error}"
+                        echo "${error}" 1>&2
                 else
                         "${modulecmd}" "${Shell}" ${opts} 'load' \
                                        "${current_modulefile}"
